/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import command.pattern.*;
/**
 *명령 전달하는 부분
 * @author 지동
 */
public class Command1 extends javax.swing.JFrame {

    public Command1() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);//종료시 화면이 꺼지지 않게하기 위해
        setTitle("명령 전달");
        setVisible(true); //화면에 보이게
        setResizable(false); //프레임 크기 조정 x
        setLocationRelativeTo(null); //프레임을 중앙으로 배치.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("굴림", 0, 25)); // NOI18N
        jLabel1.setText("명령 전달");

        jComboBox1.setFont(new java.awt.Font("굴림체", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "인사과장", "군수과장", "작전과장", "정훈장교" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Commander command = new Commander();//인보커 객체
        Personnel personnel = new Personnel();  //리시버 객체
        PersonnelCommand personnelManagement = new PersonnelCommand(personnel);
        //인사과장이 하는 일을 담당하는 ConcreteCommand 객체

        Logistics logistics = new Logistics();  //리시버 객체
        LogisticsCommand logisticsManagement = new LogisticsCommand(logistics);
        //군수과장이 하는 일을 담당하는 ConcreteCommand 객체

        Operations operations = new Operations();   //리시버 객체
        OperationsCommand readinessTraining = new OperationsCommand(operations);
        //작전과장이 하는 일을 담당하는 ConcreteCommand 객체

        JungHun jungHun = new JungHun();    //리시버 객체
        JungHunCommand jungHunManagement = new JungHunCommand(jungHun);
        //정훈장교가 하는 일을 담당하는 ConcreteCommand 객체
        
        if(jComboBox1.getSelectedIndex() == 0){ //콤보박스 리스트 첫번째 클릭시 활성화
            command.setCommand(0,personnelManagement);  //인사과장이 하는 일
            jTextArea1.setText(null);   //클릭시 내용 지우기
            jTextArea1.append(command.order(0));//인사과장이 하는 일 명령 전달
        }

        else if(jComboBox1.getSelectedIndex() == 1){    //콤보박스 리스트 두번째 클릭시 활성화
            command.setCommand(1,logisticsManagement);//군수과장이 하는 일
            jTextArea1.setText(null);//클릭시 내용 지우기
            jTextArea1.append(command.order(1));//군수과장이 하는 일 명령 전달
        }

        else if(jComboBox1.getSelectedIndex() == 2){    //콤보박스 리스트 세번째 클릭시 활성화
            command.setCommand(2,readinessTraining);//작전과장이 하는 일
            jTextArea1.setText(null);//클릭시 내용 지우기
            jTextArea1.append(command.order(2));//작전과장이 하는 일 명령 전달
        }

        else if(jComboBox1.getSelectedIndex() == 3){    //콤보박스 리스트 네번째 클릭시 활성화
            command.setCommand(3,jungHunManagement);//정훈장교가 하는 일
            jTextArea1.setText(null);//클릭시 내용 지우기
            jTextArea1.append(command.order(3));//정훈장교가 하는 일 명령 전달
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
